[theme]
primaryColor = "#FF6B35"
backgroundColor = "#000000"
secondaryBackgroundColor = "#000000"
textColor = "#FF6B35"
font = "monospace"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

